package com.xiaolv.test.db;

/**
* EbenHistoryId generated by hbm2java
*/
public class EbenHistoryEntity  implements java.io.Serializable {


  private String userid;
  private String source;
  private String ppath;
  private String name;
  private String guid;
  private Long lastUpdate;
  private Byte type;
  private Long size;
  private Character op;
  private String editor;
  private String parent;
  private Character status;
  private String srvFname;
  private String etag;
  private String omaAttr;
  private Long omaModified;
  private Long pre;

 public EbenHistoryEntity() {
 }

 public EbenHistoryEntity(String userid, String source, String ppath, String name, String guid, Long lastUpdate, Byte type, Long size, Character op, String editor, String parent, Character status, String srvFname, String etag, String omaAttr, Long omaModified, Long pre) {
    this.userid = userid;
    this.source = source;
    this.ppath = ppath;
    this.name = name;
    this.guid = guid;
    this.lastUpdate = lastUpdate;
    this.type = type;
    this.size = size;
    this.op = op;
    this.editor = editor;
    this.parent = parent;
    this.status = status;
    this.srvFname = srvFname;
    this.etag = etag;
    this.omaAttr = omaAttr;
    this.omaModified = omaModified;
    this.pre = pre;
 }

 public String getUserid() {
     return this.userid;
 }
 
 public void setUserid(String userid) {
     this.userid = userid;
 }
 public String getSource() {
     return this.source;
 }
 
 public void setSource(String source) {
     this.source = source;
 }
 public String getPpath() {
     return this.ppath;
 }
 
 public void setPpath(String ppath) {
     this.ppath = ppath;
 }
 public String getName() {
     return this.name;
 }
 
 public void setName(String name) {
     this.name = name;
 }
 public String getGuid() {
     return this.guid;
 }
 
 public void setGuid(String guid) {
     this.guid = guid;
 }
 public Long getLastUpdate() {
     return this.lastUpdate;
 }
 
 public void setLastUpdate(Long lastUpdate) {
     this.lastUpdate = lastUpdate;
 }
 public Byte getType() {
     return this.type;
 }
 
 public void setType(Byte type) {
     this.type = type;
 }
 public Long getSize() {
     return this.size;
 }
 
 public void setSize(Long size) {
     this.size = size;
 }
 public Character getOp() {
     return this.op;
 }
 
 public void setOp(Character op) {
     this.op = op;
 }
 public String getEditor() {
     return this.editor;
 }
 
 public void setEditor(String editor) {
     this.editor = editor;
 }
 public String getParent() {
     return this.parent;
 }
 
 public void setParent(String parent) {
     this.parent = parent;
 }
 public Character getStatus() {
     return this.status;
 }
 
 public void setStatus(Character status) {
     this.status = status;
 }
 public String getSrvFname() {
     return this.srvFname;
 }
 
 public void setSrvFname(String srvFname) {
     this.srvFname = srvFname;
 }
 public String getEtag() {
     return this.etag;
 }
 
 public void setEtag(String etag) {
     this.etag = etag;
 }
 public String getOmaAttr() {
     return this.omaAttr;
 }
 
 public void setOmaAttr(String omaAttr) {
     this.omaAttr = omaAttr;
 }
 public Long getOmaModified() {
     return this.omaModified;
 }
 
 public void setOmaModified(Long omaModified) {
     this.omaModified = omaModified;
 }
 public Long getPre() {
     return this.pre;
 }
 
 public void setPre(Long pre) {
     this.pre = pre;
 }


public boolean equals(Object other) {
      if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EbenHistoryEntity) ) return false;
		 EbenHistoryEntity castOther = ( EbenHistoryEntity ) other; 
      
		 return ( (this.getUserid()==castOther.getUserid()) || ( this.getUserid()!=null && castOther.getUserid()!=null && this.getUserid().equals(castOther.getUserid()) ) )
&& ( (this.getSource()==castOther.getSource()) || ( this.getSource()!=null && castOther.getSource()!=null && this.getSource().equals(castOther.getSource()) ) )
&& ( (this.getPpath()==castOther.getPpath()) || ( this.getPpath()!=null && castOther.getPpath()!=null && this.getPpath().equals(castOther.getPpath()) ) )
&& ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
&& ( (this.getGuid()==castOther.getGuid()) || ( this.getGuid()!=null && castOther.getGuid()!=null && this.getGuid().equals(castOther.getGuid()) ) )
&& ( (this.getLastUpdate()==castOther.getLastUpdate()) || ( this.getLastUpdate()!=null && castOther.getLastUpdate()!=null && this.getLastUpdate().equals(castOther.getLastUpdate()) ) )
&& ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) )
&& ( (this.getSize()==castOther.getSize()) || ( this.getSize()!=null && castOther.getSize()!=null && this.getSize().equals(castOther.getSize()) ) )
&& ( (this.getOp()==castOther.getOp()) || ( this.getOp()!=null && castOther.getOp()!=null && this.getOp().equals(castOther.getOp()) ) )
&& ( (this.getEditor()==castOther.getEditor()) || ( this.getEditor()!=null && castOther.getEditor()!=null && this.getEditor().equals(castOther.getEditor()) ) )
&& ( (this.getParent()==castOther.getParent()) || ( this.getParent()!=null && castOther.getParent()!=null && this.getParent().equals(castOther.getParent()) ) )
&& ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
&& ( (this.getSrvFname()==castOther.getSrvFname()) || ( this.getSrvFname()!=null && castOther.getSrvFname()!=null && this.getSrvFname().equals(castOther.getSrvFname()) ) )
&& ( (this.getEtag()==castOther.getEtag()) || ( this.getEtag()!=null && castOther.getEtag()!=null && this.getEtag().equals(castOther.getEtag()) ) )
&& ( (this.getOmaAttr()==castOther.getOmaAttr()) || ( this.getOmaAttr()!=null && castOther.getOmaAttr()!=null && this.getOmaAttr().equals(castOther.getOmaAttr()) ) )
&& ( (this.getOmaModified()==castOther.getOmaModified()) || ( this.getOmaModified()!=null && castOther.getOmaModified()!=null && this.getOmaModified().equals(castOther.getOmaModified()) ) )
&& ( (this.getPre()==castOther.getPre()) || ( this.getPre()!=null && castOther.getPre()!=null && this.getPre().equals(castOther.getPre()) ) );
}

public int hashCode() {
      int result = 17;
      
      result = 37 * result + ( getUserid() == null ? 0 : this.getUserid().hashCode() );
      result = 37 * result + ( getSource() == null ? 0 : this.getSource().hashCode() );
      result = 37 * result + ( getPpath() == null ? 0 : this.getPpath().hashCode() );
      result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
      result = 37 * result + ( getGuid() == null ? 0 : this.getGuid().hashCode() );
      result = 37 * result + ( getLastUpdate() == null ? 0 : this.getLastUpdate().hashCode() );
      result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
      result = 37 * result + ( getSize() == null ? 0 : this.getSize().hashCode() );
      result = 37 * result + ( getOp() == null ? 0 : this.getOp().hashCode() );
      result = 37 * result + ( getEditor() == null ? 0 : this.getEditor().hashCode() );
      result = 37 * result + ( getParent() == null ? 0 : this.getParent().hashCode() );
      result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
      result = 37 * result + ( getSrvFname() == null ? 0 : this.getSrvFname().hashCode() );
      result = 37 * result + ( getEtag() == null ? 0 : this.getEtag().hashCode() );
      result = 37 * result + ( getOmaAttr() == null ? 0 : this.getOmaAttr().hashCode() );
      result = 37 * result + ( getOmaModified() == null ? 0 : this.getOmaModified().hashCode() );
      result = 37 * result + ( getPre() == null ? 0 : this.getPre().hashCode() );
      return result;
}

@Override
public String toString() {
	return "EbenHistoryEntity [userid=" + userid + ", source=" + source + ", ppath=" + ppath + ", name=" + name
			+ ", guid=" + guid + ", lastUpdate=" + lastUpdate + ", type=" + type + ", size=" + size + ", op=" + op
			+ ", editor=" + editor + ", parent=" + parent + ", status=" + status + ", srvFname=" + srvFname + ", etag="
			+ etag + ", omaAttr=" + omaAttr + ", omaModified=" + omaModified + ", pre=" + pre + "]";
}   


}



